name: pla_net
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - cudatoolkit=11.6
  - pip
  - pip:
    - torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.13.1+cu116.html
    - torch-sparse -f https://data.pyg.org/whl/torch-1.13.1+cu116.html
    - torch-cluster==1.6.0 -f https://data.pyg.org/whl/torch-1.13.1+cu116.html
    - torch-spline-conv==1.2.1 -f https://data.pyg.org/whl/torch-1.13.1+cu116.html
    - torch-geometric==2.1.0 -f https://data.pyg.org/whl/torch-1.13.1+cu116.html
    - rdkit-pypi==2021.9.3
    - modlamp==4.3.0
    - ogb==1.3.6
    - tqdm==4.63.0
    - h5py==3.11.0
    - scipy==1.9.0
    - numpy==1.24.4
    - gradio==4.43.0
    - fastapi==0.112.4
    - jinja2==3.1.4
    - jupyter