name: pla_net
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.12.0
  - torchvision=0.13.0
  - torchaudio=0.12.0
  - cudatoolkit=11.6
  - pip
  - pip:
    - torch-scatter==2.0.9
    - torch-sparse==0.6.14
    - torch-cluster==1.6.0
    - torch-spline-conv==1.2.1
    - torch-geometric==2.1.0
    - rdkit-pypi==2021.9.3
    - modlamp==4.3.0
    - ogb==1.3.6
    - tqdm==4.63.0
    - h5py==3.11.0
    - scipy==1.9.0
    - numpy==1.24.4
    - gradio==4.43.0
    - fastapi==0.112.4